
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      // Inserts seed entries
      return knex('books').insert([
        {id: 1, genre_id: 2, theme_id: 3, name: 'Kingdom of Ash', picture: '/assets/img/book1.jpg', price: 9.64, abstract: 'A house abandoned for years, on the outskirts of Milan. Two charred corpses, no clue, no motive. This is the problem that commissioner Luca Betti must unravel, in one of the most complicated periods of his life. The separation from his wife and the difficult relationship with his daughter bring down those weak certainties of being able to count on stable affections. But there is no time for personal pain, resolving the investigation is the only priority that can give a purpose to his life and make him feel alive again. Marco Tanzi has become a successful private investigator. He seems to have left behind the terrible experiences he experienced in recent years, but the reality is quite different. To escape his personal ghosts, he accepts a case that threatens to make him slip back into the nightmares of his darkest past. He has to trace an eighteen-year-old with mental problems, the son of a Milanese upper-class couple, who fled to live among the homeless. And when a ruthless serial killer starts massacring homeless people with razor bumps, his investigation turns into a race against time. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever'},
        {id: 2, genre_id: 3, theme_id: 4, name: 'Nero a Milano', picture: '/assets/img/book2.jpg', price: 12.3, abstract: 'A house abandoned for years, on the outskirts of Milan. Two charred corpses, no clue, no motive. This is the problem that commissioner Luca Betti must unravel, in one of the most complicated periods of his life. The separation from his wife and the difficult relationship with his daughter bring down those weak certainties of being able to count on stable affections. But there is no time for personal pain, resolving the investigation is the only priority that can give a purpose to his life and make him feel alive again. Marco Tanzi has become a successful private investigator. He seems to have left behind the terrible experiences he experienced in recent years, but the reality is quite different. To escape his personal ghosts, he accepts a case that threatens to make him slip back into the nightmares of his darkest past. He has to trace an eighteen-year-old with mental problems, the son of a Milanese upper-class couple, who fled to live among the homeless. And when a ruthless serial killer starts massacring homeless people with razor bumps, his investigation turns into a race against time. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever. While a darker sky looms over the city than ever, the roads of the two friends and former colleagues will inevitably cross again. And they will find themselves, once again, in front of painful choices destined to mark their lives forever. '},
        {id: 3, genre_id: 5, theme_id: 5, name: 'Hurricane Season', picture: '/assets/img/book3.jpg', price: 14.87, abstract: 'The brutal murder of Claudia Longo, a single fifty-year-old in the exclusive Parioli district of Rome, seems to be the work of an occasional lover. One of many that the woman used to host at home. The only one not to think so is the commissioner Laura Damiani, returned to the capital after a devastating work experience in Milan. The policewoman discovers connections between that murder and the apparently accidental deaths of other single women. The victims were all customers of a refined meeting place in the Eur neighborhood, the Single. The only way Laura has to see clearly is to infiltrate the premises, as a client, without the knowledge of her superiors. It will be the beginning of a hallucinatory journey into the mysteries of a night life made up of transgression, vice, unmentionable secrets. Laura will have the opportunity to look within itself and to measure oneself with one\'s solitude and the ghosts of an existence perpetually at the crossroads between total dedication to work and the choice of a more fulfilling personal life. But he will also have to deal with another reality: there is still a killer in circulation. And her next goal seems to be her ...'},
        {id: 4, genre_id: 4, theme_id: 2, name: 'Indecent Advances', picture: '/assets/img/book4.jpg', price: 19.4, abstract: 'A skillful hybrid of true crime and social history that examines how popular culture, the media, and the psychological profession portrayed crimes against gay men in the years leading up to the Stonewall Riots'},
        {id: 5, genre_id: 1, theme_id: 1, name: 'The Number of Love', picture: '/assets/img/book5.jpg', price: 14.56, abstract: 'Three years into the Great War, England’s greatest asset is their intelligence network—field agents risking their lives to gather information, and codebreakers able to crack every German telegram. Margot De Wilde thrives in the environment of the secretive Room 40, where she spends her days deciphering intercepted messages.'},
      ]);
    });
};
